const cartAT = {

  SEND_CART: 'SEND_CART',
  POST_SEND_CART: 'POST_SEND_CART',
  INCREMENT_CART: 'INCREMENT_CART',
  DECREMENT_CART: 'DECREMENT_CART',
  DELETE_ONE_POSITION: 'DELETE_ONE_POSITION',
  INIT_ERROR_CART: 'INIT_ERROR_CART',
};

export default cartAT;
