const categoriesAT = {

  INIT_CATEGORIES: 'INIT_CATEGORIES',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_FETCH_CATEGORIES: 'GET_FETCH_CATEGORIES',
  
  INIT_ERROR_CATEGORIES: 'INIT_ERROR_CATEGORIES',
};

export default categoriesAT;
